### ISSUE TITLE
Load event seems redundant

### ISSUE THREAD

**Issue by joostf** [jeroentvb/web-app-from-scratch-18-19#7] opened 2019-02-08 14:40 UTC
Module scripts are deferred by default.

https://github.com/jeroentvb/web-app-from-scratch-18-19/blob/49d8394dfbf904bd3ce5e842346967f6ce5db810/week1/public/js/app.js#L16-L27

**Comment by jeroentvb** [comment] 2019-02-08 19:25
Although this is a duplicate of #4, I didn't know module scripts are deferred by default.
Thanks for pointing it out 👍

**Closed as completed by jeroentvb** 2019-02-08 19:25 UTC
