### ISSUE TITLE
Use const

### ISSUE THREAD

**Issue by Arash217** [jeroentvb/web-app-from-scratch-18-19#5] opened 2019-02-08 12:26 UTC
https://github.com/jeroentvb/web-app-from-scratch-18-19/blob/49d8394dfbf904bd3ce5e842346967f6ce5db810/week1/public/js/app.js#L11

sol doesn't get reassigned right? Use const instead.

**Comment by jeroentvb** [comment] 2019-02-08 17:22
Duplicate of #3

**Closed as completed by jeroentvb** 2019-02-08 17:22 UTC
